### ISSUE TITLE
Lost all data after update to 0.4.10

### ISSUE THREAD

**Issue by vdkassio** [GChristensen/scrapyard#18]
After a manual update to latest version (0.4.10), the tree with previously saved webpages is empty.
When browsing DB contents under "Indexed DB" I see hundreds of links.
How to restore the data ?
I tried uninstall, install 0.4.8, 0.4.9, restart firefox with no success.

**Comment by GChristensen** [comment]
It seems that this is a tree-view or some startup issue. The issue may be not related to the addon at all, since the dropbox integration also fails, and the dropbox auth key is stored in a different database (even a different kind of database). At first, we need to understand what is wrong. The only way to accomplish this is to get some debug information. You need to:
- Close Scraypard sidebar if it is opened
- Close Firefox
- Start it again
- Open a new tab and enter the following URL: **about:debugging**
- At this page click "This Firefox" at the top left
- Find the Scrapyard addon and click "Inspect"
- On the opened page click the "Console" tab at the top row
- Open Scrapyard sidebar
- Post the contents of the console here.

**Comment by vdkassio** [comment]
Thanks for the prompt answer. There is the debug info:

==> background.js loaded background.js:313:9
==> savepage/background.js loaded background.js:1227:9
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    send moz-extension://1d63f433-1206-4475-8b8a-7f7883de2dda/lib/Messages.js:65
Messages.js:65:35
... (around 730 lines)
Uncaught (in promise) undefined 5

After opening scrapyard sidebar:

sendRemoveListener on closed conduit treestyletab@piro.sakura.ne.jp.274877924061 ConduitsChild.jsm:108
Content Security Policy: Couldn’t process unknown directive ‘navigation-to’
==> sidebar.js loaded sidebar.js:713:9

The same is with disabled treestyletab.

**Comment by GChristensen** [comment]
If this is everything, it seems, that there is nothing wrong. As I understand, Japanese character encoding may appear in the links, so the tree component may err on it and this requires further investigation. Currently, anything could be imported from Scrapyard only if the tree is filled, so the only way to get something out of DB is JS trickery. The following code being inserted into the bottom line of the console opened in the way described before (you also need to press RETURN after you pasted it) will print the content of the entire DB as a string, so you may copy it and hence get the data in JSON form.

```javascript
var _db = indexedDB.open("scrapyard")
_db.onsuccess = function(event) {
  var db = event.target.result;
  var rows_req = db.transaction(["nodes"]).objectStore("nodes").getAll();
  rows_req.onsuccess = function(rows_evt) {
   rows_req.result.map(r => JSON.stringify(r));
   console.log(rows_req.result.map(r => JSON.stringify(r)).join("\n"));
  }
```
}

**Comment by vdkassio** [comment]
the second code returned thousands of lines that I couldn't copy/paste.
But it looks more like a history list of opened tabs/urls. 
I suspect that when updated several plugins treestyletab, scrapyard and some others something happened to the IndexDB.
Is there a way to filter only the scraped data ?
I had created some folders with subfolders (maybe not in the default).

**Comment by GChristensen** [comment]
If you'd learn enough javascript, everything its possible. The following code will return only links that have archived content, but not the content itself (it is stored in a different table which requires a more tircky query):

```javascript
var _db = indexedDB.open("scrapyard")
_db.onsuccess = function(event) {
  var db = event.target.result;
  var rows_req = db.transaction(["nodes"]).objectStore("nodes").getAll();
  rows_req.onsuccess = function(rows_evt) {
   rows_req.result.map(r => JSON.stringify(r));
   console.log(rows_req.result.filter(r => r.type == 4).map(r => r.name + " ||| " + r.uri).join("\n"));
  }
}
```

This is the only thing I can do for you, since anything else requires an awful amount of work.
If you can remember links you bookmarked/archived and the database seem ruined after this, please post them, if you do not mind. I'll try to replicate this in my environment.

**Comment by vdkassio** [comment]
There is no content of type:4 
Why do I have 5700 records of type:3 ??
I don't have so many bookmarks.
Why storage/default/moz-extension+++3d1349c3-ce5f-44a1-b36d-bbf050c0febd/idb/11793948sdcrraayp.sqlite is 8 MB ?

**Comment by vdkassio** [comment]
There is no content of type:4
Why do I have 5700 records of type:3 ??
I don't have so many bookmarks.
Why storage/default/moz-extension+++3d1349c3-ce5f-44a1-b36d-bbf050c0febd/idb/11793948sdcrraayp.sqlite is 8 MB ?

**Comment by GChristensen** [comment]
Unfortunately, this means that you have lost all the archived content (if there was any) and I can not do anything. The other records may come from ordinary firefox bookmarks. It is a fascinating number, and since Firefox bookmark API is very slow, processing may hang there (if you really have this amount of ordinary bookmarks), and it may take hours (days and literally years) to fill the tree in this case. If these are some lost bookmarks instead, IDB has become a mess and it is hard to do anything with them anyway. 
Well, it seems that users with large amount of ordinary firefox bookmarks require special treatment (probably, Firefox bookmark integration should not be enabled by default).

**Comment by vdkassio** [comment]
I don't use bookmarks. I probably have 10-15.
Only scraping. And not so much (100-150).
Is it possible that some other plugin (like STG - Simple Tab Groups) has written all this ?
If there is no simple (auto)backup and no way to recover, then the scrapyard plugin is not usable in production.

**Comment by vdkassio** [comment]
You didn't explain from where are those records type:3
Are logging all opened pages ?

**Comment by GChristensen** [comment]
>You didn't explain from where are those records type:3

I've explained - the only way they may get there is through the ordinary Firefox bookmark integration, or they may be lost bookmarks that are not connected to any existing root of the bookmark tree. I'm not logging any user activity, which you may check in the code of the addon itself. Nothing other could write into the addon DB.

By the way, this is what you get when you use software written by enthusiasts. More prominent workshops, such as Microsoft, have more resources for testing, and since I'm the only developer (I use Scrapyard more than a year without any excesses), users are the final frontier of testing.

You may turn off Firefox bookmark integration and give it a try (to delete everything from DB you need to remove the addon, restart Firefox, and install the addon again; if there will be anything in DB after the reinstall, you need to check if the addon ID, which you may find in the URL of the settings page, has changed, and wait more between Firefox restarts if it has not). It is interesting how it will work without Firefox bookmark integration since we found nothing wrong in the working of the addon itself except for the lost entries.
