### ISSUE TITLE
Scrapyard archive search in content not working

### ISSUE THREAD

**Issue by timlt-scratch** [GChristensen/scrapyard#19]
Installed latest Scrapyard extension on Firefox 78.0.2 running on Win10 x64 Pro.

Everything works except search in archive content.  Try setting different contexts:  title, tags, content.  Works for title and tags.  But search in content returns nothing.

**Comment by GChristensen** [comment]
Thanks for the report. There was a bug in the regex that parses content to distinct words, that take into account only Latin characters. This is fixed now, but there may still be problems for Asiatic languages since there is currently no easy way to break such content to words with regular expressions. You also need to re-archive all relevant non-Latin pages to search by content in them, since the existing indexes do not contain any non-Latin words.
