### ISSUE TITLE
Database export failed

### ISSUE THREAD

**Issue by Robby-Jo** [GChristensen/scrapyard#36]
Two questions regarding Scrapyard:

1. Is there a limit to the size of the database (e.g. to 2 GB)?
2. When I want to export my (approx. 2 GB) database under scrapyard 0.7.1, I recently get the error message "_The export has failed_". Is the database too big?

Regards,

Stephan

**Comment by GChristensen** [comment]
Currently, if the helper application is not installed, all exported items are stored in memory (because Mozilla removed the ability to create random access files in local storage). Please try to export with the helper application installed.
If you do this for backup purposes, it is more convenient to backup the entire Firefox profile with the third-party backup software.

**Comment by Robby-Jo** [comment]
Thank you for your support!
