### ISSUE TITLE
QuotaExeededError importing a shelf

### ISSUE THREAD

**Issue by ilochab77** [GChristensen/scrapyard#4]
I succesfully imported my old SrapBook's data into Scrapyard using Windows.
Now I'm trying to export them to import later on linux, because I wasn't able to do that there.
At each export command I get a json file with a different size.
So I'm tring to import back on a different shelf, always on windows, just to check if everything was exported.
As soon as I launch the import command I get an error that says:
The import has failed: QuotaExeededError
The current transaction exeeded its quota limitation.
(I think that at the first run the sentence was sligtly different).
Perahps there is a size limitation? 
What can I do to solve my problem?

**Comment by GChristensen** [comment]
Hi,

This must be a storage space quota, and since the addon requires "unlimitedStorage" permission, this may be some setting in your profile, that overrides this. The only thing I can suggest is to check for global system settings that may affect Firefox local storage and try to import on a clean profile.

**Comment by ilochab77** [comment]
Thank you for the speedy answer. I'll try asap.

Il Mar 31 Dic 2019, 23:29 GChristensen <notifications@github.com> ha
scritto:
