### ISSUE TITLE
So Much Probmise, but....

### ISSUE THREAD

**Issue by BrendaEM** [GChristensen/scrapyard#43]
I tried an earlier version of Scrapyard, and became optimistic because it was the first extension that I thought capable of carrying the torch for Scrapbook. I imported my old scrapbook data, and did some work to weed the old stuff out. I needed to reinstall, so I made sure I had a back up the data. I reinstalled on the system, and my attempts to restore my effort has failed, with a Loading... 

I had no problem with the old Scrapbook, for years.

What I wished would happen:

1.) Scrapbook would use extensions its file saves--unless the goal is not to hide a user's data from themselves for some nefarious purpose.
2.) There was a straightforward backup/restore function, or perhaps a sync one.

Thank you for working on Scrapyard. I look forward to using it.

**Comment by GChristensen** [comment]
Sorry, but I could not understand what exactly happened from the description. If you have imported a backed up JSON file and Scrapyard shows "Loading...", to debug this, please close the Scrapyard sidebar, open the following URL: **about:devtools-toolbox?id=scrapyard-we%40firefox&type=extension** , open the Console tab there, open Scrapyard sidebar, and post here the content that was printed in the console after you have opened the sidebar.

**Comment by GChristensen** [comment]
Well...

>Scrapbook would use extensions its file saves--unless the goal is not to hide a user's data from themselves for some nefarious purpose.

It turns out that for a couple of weeks there was a horrible bug between version 0.11.7 and 0.11.8, which rendered all exports useless if no helper application was installed. Since I use the helper application myself and low on resources (can only dream of proper QA), it has escaped my testing routine. I do not do such things on purpose, this is a sad byproduct of the attempts to make the addon more performant and memory-efficient. Since I advertise backup whenever I can, you should have backups older than the last couple of weeks, which should work (but you may need to uninstall the add-on, restart Firefox, and install it again, if older backups do not work). Such a thing would have not happened if you have backed up your entire Firefox profile before system reinstallation.

>There was a straightforward backup/restore function, or perhaps a sync one.

I added a backup management UI in the addon settings, which is a decent piece of work. Please do not forget to donate, if you have good use of the software.
