### ISSUE TITLE
[Feature request] Information panel how in Scrapbook

### ISSUE THREAD

**Issue by Xiomber** [GChristensen/scrapyard#44]
Please add a Information panel like the one in Scrapbook (with the ability to enable - disable the panel in the settings and hotkeys). This is the panel at the bottom of the archived page with URL of the saved site, by clicking on which will go to the original site. It would be ideal that she was the same size as Information panel in the Scrapbook. It would be nice if the panel was date and time when the site was saved, as well as the size of the archived site. 
For example: 
**https://www.site.com Added on: 27 Apr 2021 00:00:00 Size: 3.55 MB**

**Comment by GChristensen** [comment]
You may not believe it, but there is already such a toolbar, and it also already pretty crowded: 

![edit-bar](https://user-images.githubusercontent.com/170405/118130494-788d4c80-b40e-11eb-86fb-5d07917a0eea.png)

But before v0.12 it was a matter of probability if it is displayed on some heavy pages. In v0.12 it is guaranteed to be displayed on all new saved pages, and also old ones (with a probability of 98.6% or so, because some problems may be solved only asymptotically). Because it is pretty reasonable to have page size on such a toolbar, I added a humble icon at a humble place (highlighted yellow on the image below); by hovering the mouse pointer over it you may get a tooltip with the date and page size.

Please do not forget to donate if you have good use of the software.
