### ISSUE TITLE
Dark background in full-text search

### ISSUE THREAD

**Issue by Xiomber** [GChristensen/scrapyard#45]
Hello. When using full-text search on saved sites Envato Market, https://themeforest.net etc, a dark background appears, obscuring the text content of almost the entire page. It can be fixed?

**Comment by GChristensen** [comment]
Can not reproduce this issue for this link, but full text search for the sites from the earlier issue does not work, probably due to the insufficient stack size of regular expression engine (CSS/scripts used by them and the size of images are enormous). Nothing could be done, since there are fundamental limits of what JS regex engine can handle.
