### ISSUE TITLE
Incorrect saving of web pages

### ISSUE THREAD

**Issue by Xiomber** [GChristensen/scrapyard#46]
Hello. Scrapyard does not correctly save some web pages. For example here, elements of the page duplicate each other and break the structure of the page itself:
https://preview.themeforest.net/item/goya-modern-woocommerce-theme/full_screen_preview/25175097?_ga=2.137797433.821234341.1626253755-1257140990.1626206347

Here does not keep preload, is not saved the whole block in the center of the page after "Demo websites. Single click install."
https://preview.themeforest.net/item/ohio-creative-wordpress-theme/full_screen_preview/25193838?_ga=2.1750006.611586332.1626270673-1257140990.1626206347

Sliders and animations do not work on both saved sites

**Comment by GChristensen** [comment]
1) I suppose that the first image is generated by script, the second is contained in a <noscript> tag. Since scripts are enabled on the page generally, but may be not enabled, as well as enabled when the archive page is viewed, I see no idiomatic way to fix this. The one possible way is to edit page (or its HTML) after it was saved.

2) The images after "Demo websites" are dynamically loaded from server, which obviously is senseless for archived pages (if scripts are enabled for archives they still may fail due to the differences in saved HTML). No fix is required.
