### ISSUE TITLE
Scrapyard

### ISSUE THREAD

**Issue by Kordaroy** [GChristensen/scrapyard#48]
Scrapyard Diagnostics

Please do not try to reinstall the add-on. Create an issue at the Scrapyard support page with the info below.

Error name: OpenFailedError
Error message: InvalidStateError A mutation operation was attempted on a database that did not allow mutations.
Origin: Sidebar initialization

Stacktrace

OpenFailedError: InvalidStateError A mutation operation was attempted on a database that did not allow mutations.

**Comment by GChristensen** [comment]
This does not look like as an error in Scrapyard, since the stack trace shows no functions called. Most likely, this is the problem with Firefox and antivirus, described on the addon page. Please try to add the addon DB path (could be found at ext+scrapyard://advanced ) to the antivirus exceptions or change your antivirus, if you have any.
