### ISSUE TITLE
Slower Firefox startup when Scarpyard has many web pages saved

### ISSUE THREAD

**Issue by Robby-Jo** [GChristensen/scrapyard#49]
I saved quite a lot of websites with Scrapyard, the backup size is about 1 Gbyte. For some time now I have been observing that Firefox (64 bis, current version) takes a very long time to start, around 1 minute to 3 minutes. I suspect this is due to Scarpyard. If I prevent the loading of Scrapyard in the Firefox settings, Firefox starts again as quickly as usual. Do I need to delete saved pages in Scrapyard to reduce Firefox loading time :-( or is there a better way?

I usually close Firefox when a few tabs are open and after the restart I have these tabs displayed again. By load time I mean the amount of time it takes for Firefox to load the tabs. The delay occurs even if no Scarpyard tab needs to be restored.

**Comment by GChristensen** [comment]
Firefox checks all its local storage cache during the startup and is unresponsive at this time. Because Scrapyard uses local storage to store saved content, the large amount of saved pages adds to the startup idle time. There is probably no way to aid this problem, unless the cache checking behavior will be fixed by the Firefox developers. As a workaround it is possible to restart Firefox as less as possible and use OS hibernate option.
