### ISSUE TITLE
Scrapyard: An addon that never should have existed 

### ISSUE THREAD

**Issue by grotesque** [GChristensen/scrapyard#58]
I like author's ideas here: https://gchristensen.github.io/posts/creating-personal-knowledge-base/

But I think he's making bad architecture/design decisions. This is seen in his comments like:
`restart Firefox as less as possible and use OS hibernate option (to avoid the issue of slow startup)`

My gripes with the addon:

**Default storage in some weird Mozilla object store**

The addon states at start itself that "Scrapyard does not require installing external tools for most of its functionality by keeping the data in the browser internal storage". But wtf is internal storage? How many of us know about object stores and blobs? What we know are files. The idea that the author of addon wants me to put everything inside firefox's database itself and not simple files which I can move around and do whatever the hell I want is preposterous. 

Is the object store scalable? What are its limits? Does clearing cache deletes the data? So many questions. So much unnecessary complexity.

My scrapbook db is 15GB+. It has a million files. This addon can obviously not handle that.

**Search**

Doesn't do substring level search on content. Deal breaker for me.

Example https://github.com/freeCodeCamp/freeCodeCamp 
If I want to find a project named codecamp and its webpage calls it freecodecamp. I don't want to be punished for not remembering the word "free". This is searching. I'm "searching" because I've forgotten knowledge. The search should make it as easy as possible to locate the idea that I want it to find. Substring search is a very basic thing. The thought that author chooses to ignore it makes me question his software design skills.

**Installation of helper app**

It's a mess. On WIndows the MSI just didn't work for me. The other one did but I made folders in "C:\Users\Administrator\AppData\Roaming\Python\Python310\Scripts" and I don't know where else. It also kept 2 process always running in the background. All this would be tolerable but I found no way to restart the helper service after I exit firefox. I have to run the installer again to start those 2 processes. Idiotic.

Also webscrapbook exists on chrome. Even with its clunky sidebar (thanks google) it's still more like scrapbook itself than this.

**Comment by GChristensen** [comment]
Thanks for your opinion. In software design every decision faces compromises concerning with which APIs or options are available. The landscape of APIs when Scrapyard was created was a little bit different from the current one. Due to this fact, the resulting product may not satisfy all user requirements. In a free market users are free to choose the solution that fits their needs most adequately.

>Default storage in some weird Mozilla object store

This decision brings its own compromises. Yes, it is hard to import large archives into it, but it gives freedom from the external tools. The removal of IDBMutableFile and file:// protocol access from Firefox WebExtensions reduced this freedom, so Scrapyard now could do less without the external tools that it could before.

>Is the object store scalable? What are its limits? Does clearing cache deletes the data? So many questions. So much unnecessary complexity.

Theoretically it scales to the 50% of the disk space. It persistent in the case of cache cleaning.

>Doesn't do substring level search on content. 

This is the limitation of how IndexedDB indexes work. They can quickly filter only beginnings of the words. This is a compromise between the search speed and completeness. It is possible to add an option to perform the complete full-text search (and I probably will add it), although its time will be astronomical, especially in 15GB+ databases.

>Installation of helper app
>On WIndows the MSI just didn't work for me.

I do not provide MSI. The installer is made with NSIS. Are you GPT-3, writing derogatory posts :)?

>C:\Users\Administrator

This indicates that you executed it in the elevated command prompt. The helper app is a regular python package that installs in the Python user's site scripts folder. Try to use it in a non-elevated shell. The fact that the helper does not exit after Firefox may point at antivirus again.

And finally
>restart Firefox as less as possible and use OS hibernate option (to avoid the issue of slow startup)

Is just an advice on the matter that is out of control for WebExtension developers. If it makes to think badly about them, it is reasonable to just delete this Q&A item.

Thanks again for your opinion. I'll think more on what I could do with Scrapyard.

**Comment by grotesque** [comment]
>  it gives freedom from the external tool

scrapyard _needs_ an external tool for 50% of its functionality already.

>  removal of IDBMutableFile and file:// protocol access from Firefox WebExtensions reduced this freedom

I don't know what those are. What I do know is [webscrapbook ](https://addons.mozilla.org/en-US/firefox/addon/webscrapbook/) works decently and it's able to save files outside the object-store. But it has gotten clunky. i.e. the GUI sucks. It's slow. Everything feels like it's floating. scrapyard's UI is excellent. 

>  the limitation of how IndexedDB indexes work

I don't know what those are. What I know is Scrapbook used to find anything in my 15GB+ database in a second. It did this after updating full-text-cache which took a minute. But I could work with older full-text-cache if I didn't wanted to wait.

My point is architectural design decisions are flawed in most modern software. eg. We are here talking because of the idiocy of Mozilla. Yours is another ripe example.

>  I do not provide MSI. The installer is made with NSIS

I don't know what framework you use. I was talking about [this](https://github.com/GChristensen/scrapyard/releases/download/v1.2/scrapyard-helper-1.2_x86_64.exe). It did not work. Many people call those things MSI. [Example](https://www.7-zip.org/download.html).

[This](https://github.com/GChristensen/scrapyard/releases/download/v1.2/scrapyard-helper-1.2.tgz) worked but it made files at some weird places on my disk. I don't like it. Why can't it stay inside its own folder?

>  The fact that the helper does not exit after Firefox may point at antivirus again

No. The helper exits after Firefox exits but it doesn't start when Firefox starts. I have to run the installer again to get the helper to start.

>  I'll think more on what I could do with Scrapyard.

You clearly are a very bright person. Android app idea is great. But it makes Scrapyard almost like evernote+evernote-web-clipper: **nothing is stored locally as file**. I think you should stop getting influenced by modern software design.

**Comment by GChristensen** [comment]
>Scrapyard's UI is excellent.

That is largely because everything is stored inside a database. It is much faster and handy to operate with single blobs than a bunch of RDF/HTML files. Another compromise.

>I don't know what framework you use. I was talking about [this](https://github.com/GChristensen/scrapyard/releases/download/v1.2/scrapyard-helper-1.2_x86_64.exe). It did not work.

How exactly? Have it installed to the chosen destination? There should also be key HKEY_CURRENT_USER\SOFTWARE\Mozilla\NativeMessagingHosts\scrapyard_helper in the registry. Was it created? If not, an antivirus may be a hindrance.

>[This](https://github.com/GChristensen/scrapyard/releases/download/v1.2/scrapyard-helper-1.2.tgz) worked but it made files at some weird places on my disk. I don't like it. Why can't it stay inside its own folder?

That is probably due to the idiocy of Python developers, who decided that they should store library files somewhere that are generally downloaded from PyPi.org. And the helper uses the milder option by installing in user's directory. Generally, Python packages files are installed in the Python location at Program Files. Why Python, after all? Sorry about that. You may rightfully do not like this decision. Package is necessary to generate binary that will be picked up by Firefox. WebScrapbook has not the automation of the backend lifecycle.

>The helper exits after Firefox exits but it doesn't start when Firefox starts.

That's quite interesting. It works as expected (starts when Firefox stars) on a machine without an antivirus. One possible reason that key HKEY_CURRENT_USER\SOFTWARE\Mozilla\NativeMessagingHosts\scrapyard_helper is deleted somehow (probably by antivirus).
