### ISSUE TITLE
[Issue] No video with supported format and MIME type found

### ISSUE THREAD

**Issue by Terkyz** [GChristensen/scrapyard#72]
When I try to archive a page containing a video with Scrapyard, many times the video comes up with the message "No video with supported format and MIME type found", I have tried many pages with videos, and this does not always happen.

I have come to the conclusion, that this is because there are very large videos (more than 100MB) and that is why Scrapyard is unable to archive them correctly, because the other content of the page works.

[Firefox 111.0]

**Comment by GChristensen** [comment]
It may be that this is really some video with a rare MIME-type such as Real Media handled by some JavaScript-based player. Scrapyard can only save HTML videos provided in <video> tags. There is also a limit on the maximum size of the linked files on the "Page Capture" settings "Maximum size allowed for a resource (MB)".

**Comment by Terkyz** [comment]
It is possible, in several pages I tried to archive the format of the video was webm

**Comment by GChristensen** [comment]
Well, sometime ago I tried to save MP4 videos of 1.5 GB embedded in the &lt;video&gt; tag, and it worked, although painfully slow and used a lot of RAM. It's not a wise option, because the entire video is loaded into RAM and is stored as an URL-encoded string which may take four times of the original file size. It is necessary to investigate what exactly generates this message. Possibly, some JavaScript based player.
