### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by xfound** [GChristensen/scrapyard#77]
crapyard Diagnostics

Please do not try to reinstall the add-on. Create an issue at the Scrapyard [support page](https://github.com/GChristensen/scrapyard/issues) with the info below.

Error name: Error
Error message: Could not establish connection. Receiving end does not exist.
Origin: Sidebar initialization
Browser version: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0

Stacktrace

get/<@moz-extension://e5d627a4-4873-4ad5-899e-763370e7c06a/proxy.js:124:36

**Comment by GChristensen** [comment]
>crapyard Diagnostics
...
>get/<@moz-extension://e5d627a4-4873-4ad5-899e-763370e7c06a/proxy.js:124:36

Thank you for your subtle politeness and the detailed explanations of the actions during which you've got this error. I'll try to help as soon as I can. Although, if this is the complete stack trace, I can not say anything about the error. The only thing I can suggest is to update Firefox to a newer version, since version 102 is used.
